### PR TITLE
Add patch for windows

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pull request adds a patch to correctly find the *udunits* shared library on Windows. For testing purposes, I've removed the *noarch* but will hopefully add it back in when the tests are passing.

### CODE REVIEW

**Comment by mcflugen** [comment]
@ocefpaf It turns out that *cfunits* dlopens the *udunits2* shared library, whose name depends on the platform. It looked for a *.dylib* on Mac, otherwise it looked for a *.so* file. I've added a patch so that it now looks for a *.dll* file on Windows. For testing purposes, I've removed the *noarch* but I think it should be able to be added back in.

**Comment by ocefpaf** [comment]
I pulled the other package and I'll merge this as soon as you re-add the `noarch`.

**Comment by mcflugen** [comment]
@ocefpaf Thanks! I've added the *noarch* back and the tests have passed. Hopefully this will do the trick. 🤞

**Comment by mcflugen** [comment]
Thanks @ocefpaf! All looks good. Our Windows tests that use *cfunits* are now passing. 🎉

Your help with this is much appreciated!

**Pull request merged**
