### PR TITLE
Bump version to 1.7.

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request bumps cfunits to v1.7. 1.7 works with Python 3 so I've also removed the skip for `py3k`. I think it probably also works on Windows now but I'm not certain.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Thanks @mcflugen! I re-rendered it to get the Python 3 version in the build matrix.

**Comment by mcflugen** [comment]
@ocefpaf Thank you! I notice the linux builds aren't being uploaded to Anaconda Cloud. Any ideas on why that may be?

**Comment by ocefpaf** [comment]
> I notice the linux builds aren't being uploaded to Anaconda Cloud. Any ideas on why that may be?

https://github.com/conda-forge/cfunits-feedstock/issues/4 should fix that. Old feedstock may have expired tokens so we need to refresh it.

**Comment by ocefpaf** [comment]
The packages should be in the channel now.

**Pull request merged**
