### PR TITLE
Make noarch

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pull request makes *cfunits* a noarch package.

### CODE REVIEW

**Comment by mcflugen** [comment]
@ocefpaf I would like to use this package on Windows (well, not me personally - my Windows people would like to use it). This pull request was initially intended to make *cfunits* build on Windows but I noticed that, I think, it should work just fine as a *noarch* package. I believe all of its dependencies run on Windows so that should be fine.

Does that make sense?

**Comment by ocefpaf** [comment]
> Does that make sense?

If the package does not have compiled extensions then it does makes sense. The `setup.py` imports `Extension` in the first line but I do not believe it is used. Maybe it is better to ask someone that is more familiar with the source code before merging this.

**Comment by mcflugen** [comment]
@ocefpaf Thanks. I asked you because you seemed to be the biggest contributor to the feedstock. I filed an issue with the *cfunits* developers over at *Bitbucket*. We'll see what they say.

@cehbrecht, I'm not sure what your connection is to *cfunits* but you're listed as a maintainer of the feedstock. Do you have any thoughts?

**Comment by ocefpaf** [comment]
> @ocefpaf Thanks. I asked you because you seemed to be the biggest contributor to the feedstock.

No problem. But sometimes I package so many things and I don't really know the source code in depth.

> I filed an issue with the _cfunits_ developers over at _Bitbucket_. We'll see what they say.

Thanks! If we don't get an answer we can try to merge, test, and if things are broken revert it later.

**Comment by mcflugen** [comment]
@ocefpaf It's just about been a week and I've not heard back. What do you think, should we go ahead and merge?

**Comment by ocefpaf** [comment]
> @ocefpaf It's just about been a week and I've not heard back. What do you think, should we go ahead and merge?

Let's give it a try, if it breaks the package we can remove it later.

**Pull request merged**
